# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiceRollingSimulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_DiceRollingSimulator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 601, 316))
        self.background.setStyleSheet("")
        self.background.setInputMethodHints(QtCore.Qt.ImhNone)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("PVS/Background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.BackgroundBehind_2 = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundBehind_2.setEnabled(True)
        self.BackgroundBehind_2.setGeometry(QtCore.QRect(15, 15, 571, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackgroundBehind_2.sizePolicy().hasHeightForWidth())
        self.BackgroundBehind_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.BackgroundBehind_2.setFont(font)
        self.BackgroundBehind_2.setToolTipDuration(0)
        self.BackgroundBehind_2.setAutoFillBackground(False)
        self.BackgroundBehind_2.setStyleSheet("background: rgba(35, 35, 35, 0.7);\n"
"border-radius:5px;\n"
"")
        self.BackgroundBehind_2.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.BackgroundBehind_2.setText("")
        self.BackgroundBehind_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BackgroundBehind_2.setObjectName("BackgroundBehind_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(466, 15, 121, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.help_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.help_btn.setMinimumSize(QtCore.QSize(18, 18))
        self.help_btn.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setBold(True)
        font.setWeight(75)
        self.help_btn.setFont(font)
        self.help_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_btn.setStyleSheet("background-color: rgb(5,195,221);\n"
"border-radius:8px;")
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout.addWidget(self.help_btn)
        self.pushButtonMinimize = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMinimize.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMinimize.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius:8px;")
        self.pushButtonMinimize.setText("")
        self.pushButtonMinimize.setObjectName("pushButtonMinimize")
        self.horizontalLayout.addWidget(self.pushButtonMinimize)
        self.pushButtonMaximiz = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonMaximiz.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMaximiz.setStyleSheet("background-color: rgb(255, 226, 0);\n"
"border-radius:8px;")
        self.pushButtonMaximiz.setText("")
        self.pushButtonMaximiz.setObjectName("pushButtonMaximiz")
        self.horizontalLayout.addWidget(self.pushButtonMaximiz)
        self.pushButtonExit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonExit.setStyleSheet("background-color:rgb(255, 97, 6);\n"
"border-radius:8px;")
        self.pushButtonExit.setText("")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.horizontalLayout.addWidget(self.pushButtonExit)
        self.player1 = QtWidgets.QLineEdit(self.centralwidget)
        self.player1.setGeometry(QtCore.QRect(15, 60, 136, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.player1.setFont(font)
        self.player1.setAutoFillBackground(False)
        self.player1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"\n"
"\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.player1.setText("")
        self.player1.setCursorPosition(0)
        self.player1.setAlignment(QtCore.Qt.AlignCenter)
        self.player1.setClearButtonEnabled(False)
        self.player1.setObjectName("player1")
        self.player2 = QtWidgets.QLineEdit(self.centralwidget)
        self.player2.setGeometry(QtCore.QRect(450, 60, 136, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.player2.setFont(font)
        self.player2.setAutoFillBackground(False)
        self.player2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#fdfc47, stop:1 #24fe41);\n"
"\n"
"\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.player2.setText("")
        self.player2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.player2.setCursorPosition(0)
        self.player2.setAlignment(QtCore.Qt.AlignCenter)
        self.player2.setClearButtonEnabled(False)
        self.player2.setObjectName("player2")
        self.dice2 = QtWidgets.QPushButton(self.centralwidget)
        self.dice2.setGeometry(QtCore.QRect(450, 105, 136, 136))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dice2.setFont(font)
        self.dice2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dice2.setStyleSheet("\n"
"color : rgba(220, 220,220);\n"
"border-radius:20px;\n"
"\n"
"")
        self.dice2.setText("")
        self.dice2.setIconSize(QtCore.QSize(145, 140))
        self.dice2.setObjectName("dice2")
        self.dice1 = QtWidgets.QPushButton(self.centralwidget)
        self.dice1.setGeometry(QtCore.QRect(15, 105, 136, 136))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dice1.setFont(font)
        self.dice1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dice1.setStyleSheet("\n"
"color : rgba(220, 220,220);\n"
"border-radius:20px;\n"
"\n"
"")
        self.dice1.setText("")
        self.dice1.setIconSize(QtCore.QSize(145, 145))
        self.dice1.setObjectName("dice1")
        self.resetgame1 = QtWidgets.QPushButton(self.centralwidget)
        self.resetgame1.setGeometry(QtCore.QRect(15, 255, 136, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.resetgame1.setFont(font)
        self.resetgame1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetgame1.setStyleSheet("background: rgba(0, 0, 0, 155);\n"
"color : rgba(255, 255,255);\n"
"border-radius:4px;\n"
"\n"
"")
        self.resetgame1.setObjectName("resetgame1")
        self.score1 = QtWidgets.QLabel(self.centralwidget)
        self.score1.setGeometry(QtCore.QRect(165, 60, 61, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.score1.setFont(font)
        self.score1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"\n"
"\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.score1.setAlignment(QtCore.Qt.AlignCenter)
        self.score1.setObjectName("score1")
        self.score2 = QtWidgets.QLabel(self.centralwidget)
        self.score2.setGeometry(QtCore.QRect(375, 60, 61, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.score2.setFont(font)
        self.score2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#fdfc47, stop:1 #24fe41);\n"
"\n"
"\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.score2.setTextFormat(QtCore.Qt.AutoText)
        self.score2.setAlignment(QtCore.Qt.AlignCenter)
        self.score2.setObjectName("score2")
        self.resetgame2 = QtWidgets.QPushButton(self.centralwidget)
        self.resetgame2.setGeometry(QtCore.QRect(450, 255, 136, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.resetgame2.setFont(font)
        self.resetgame2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetgame2.setStyleSheet("background: rgba(0, 0, 0, 155);\n"
"color : rgba(255, 255,255);\n"
"border-radius:4px;\n"
"\n"
"")
        self.resetgame2.setObjectName("resetgame2")
        self.back = QtWidgets.QLabel(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(0, 0, 601, 316))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setStyleSheet("background: rgba(0, 0, 0, 35);\n"
"color : rgba(200, 200,200);\n"
"border-radius:4px;\n"
"\n"
"")
        self.back.setText("")
        self.back.setTextFormat(QtCore.Qt.AutoText)
        self.back.setAlignment(QtCore.Qt.AlignCenter)
        self.back.setObjectName("back")
        self.settime = QtWidgets.QPushButton(self.centralwidget)
        self.settime.setGeometry(QtCore.QRect(240, 255, 121, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.settime.setFont(font)
        self.settime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settime.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffffff, stop:1 #abbaab);\n"
"\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.settime.setObjectName("settime")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(165, 120, 271, 112))
        font = QtGui.QFont()
        font.setFamily("Calisto MT")
        font.setPointSize(27)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setStyleSheet("background: rgba(0, 0, 0, 155);\n"
"\n"
"\n"
"color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);\n"
"border-radius:4px;\n"
"\n"
"")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.dice1lbl = QtWidgets.QLabel(self.centralwidget)
        self.dice1lbl.setGeometry(QtCore.QRect(15, 105, 136, 136))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.dice1lbl.setFont(font)
        self.dice1lbl.setStyleSheet("background: rgba(0, 0, 0, 155);\n"
"color : rgba(220, 220,220);\n"
"border-radius:20px;\n"
"\n"
"")
        self.dice1lbl.setText("")
        self.dice1lbl.setTextFormat(QtCore.Qt.AutoText)
        self.dice1lbl.setPixmap(QtGui.QPixmap("PVS/Player1/DiceP1.png"))
        self.dice1lbl.setScaledContents(True)
        self.dice1lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.dice1lbl.setObjectName("dice1lbl")
        self.dice2lbl = QtWidgets.QLabel(self.centralwidget)
        self.dice2lbl.setGeometry(QtCore.QRect(450, 105, 136, 136))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.dice2lbl.setFont(font)
        self.dice2lbl.setStyleSheet("background: rgba(0, 0, 0, 155);\n"
"color : rgba(220, 220,220);\n"
"border-radius:20px;\n"
"\n"
"")
        self.dice2lbl.setText("")
        self.dice2lbl.setTextFormat(QtCore.Qt.AutoText)
        self.dice2lbl.setPixmap(QtGui.QPixmap("PVS/Player2/DiceP2.png"))
        self.dice2lbl.setScaledContents(True)
        self.dice2lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.dice2lbl.setObjectName("dice2lbl")
        self.turn1 = QtWidgets.QLabel(self.centralwidget)
        self.turn1.setGeometry(QtCore.QRect(165, 255, 61, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.turn1.setFont(font)
        self.turn1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);\n"
"\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.turn1.setTextFormat(QtCore.Qt.AutoText)
        self.turn1.setScaledContents(True)
        self.turn1.setAlignment(QtCore.Qt.AlignCenter)
        self.turn1.setObjectName("turn1")
        self.turn2 = QtWidgets.QLabel(self.centralwidget)
        self.turn2.setGeometry(QtCore.QRect(375, 255, 61, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.turn2.setFont(font)
        self.turn2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #5488ff,stop:1 #a5fecb);\n"
"\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.turn2.setTextFormat(QtCore.Qt.AutoText)
        self.turn2.setScaledContents(True)
        self.turn2.setAlignment(QtCore.Qt.AlignCenter)
        self.turn2.setObjectName("turn2")
        self.showtime = QtWidgets.QLineEdit(self.centralwidget)
        self.showtime.setGeometry(QtCore.QRect(240, 60, 121, 36))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.showtime.setFont(font)
        self.showtime.setAutoFillBackground(False)
        self.showtime.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffffff, stop:1 #abbaab);\n"
"\n"
"\n"
"color : rgba(0, 0,0);\n"
"border-radius:4px;\n"
"\n"
"")
        self.showtime.setText("")
        self.showtime.setCursorPosition(0)
        self.showtime.setAlignment(QtCore.Qt.AlignCenter)
        self.showtime.setClearButtonEnabled(False)
        self.showtime.setObjectName("showtime")
        self.l2 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2.setEnabled(False)
        self.l2.setGeometry(QtCore.QRect(140, 85, 16, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius:4px;\n"
"\n"
"\n"
"")
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setPlaceholderText("")
        self.l2.setObjectName("l2")
        self.l2_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2_2.setEnabled(False)
        self.l2_2.setGeometry(QtCore.QRect(575, 90, 16, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l2_2.setFont(font)
        self.l2_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius:4px;\n"
"\n"
"\n"
"")
        self.l2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2_2.setPlaceholderText("")
        self.l2_2.setObjectName("l2_2")
        self.l2_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2_3.setEnabled(False)
        self.l2_3.setGeometry(QtCore.QRect(350, 90, 16, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l2_3.setFont(font)
        self.l2_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius:4px;\n"
"\n"
"\n"
"")
        self.l2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l2_3.setPlaceholderText("")
        self.l2_3.setObjectName("l2_3")
        self.l2_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2_4.setEnabled(False)
        self.l2_4.setGeometry(QtCore.QRect(350, 285, 16, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l2_4.setFont(font)
        self.l2_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius:4px;\n"
"\n"
"\n"
"")
        self.l2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l2_4.setPlaceholderText("")
        self.l2_4.setObjectName("l2_4")
        self.l2_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2_5.setEnabled(False)
        self.l2_5.setGeometry(QtCore.QRect(135, 225, 16, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l2_5.setFont(font)
        self.l2_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffff00, stop:1 #ffa733);\n"
"border-radius:4px;\n"
"\n"
"\n"
"")
        self.l2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l2_5.setPlaceholderText("")
        self.l2_5.setObjectName("l2_5")
        self.l2_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2_6.setEnabled(False)
        self.l2_6.setGeometry(QtCore.QRect(570, 225, 16, 16))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l2_6.setFont(font)
        self.l2_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#fdfc47, stop:1 #24fe41);\n"
"border-radius:4px;\n"
"\n"
"\n"
"")
        self.l2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.l2_6.setPlaceholderText("")
        self.l2_6.setObjectName("l2_6")
        self.background.raise_()
        self.back.raise_()
        self.BackgroundBehind_2.raise_()
        self.layoutWidget.raise_()
        self.player1.raise_()
        self.player2.raise_()
        self.resetgame1.raise_()
        self.score1.raise_()
        self.score2.raise_()
        self.resetgame2.raise_()
        self.settime.raise_()
        self.result.raise_()
        self.dice1lbl.raise_()
        self.dice1.raise_()
        self.dice2lbl.raise_()
        self.dice2.raise_()
        self.turn1.raise_()
        self.turn2.raise_()
        self.showtime.raise_()
        self.l2.raise_()
        self.l2_2.raise_()
        self.l2_3.raise_()
        self.l2_4.raise_()
        self.l2_5.raise_()
        self.l2_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButtonExit.clicked.connect(MainWindow.close)
        self.pushButtonMinimize.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dice Rolling Simulator"))
        self.help_btn.setText(_translate("MainWindow", "H"))
        self.player1.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.player1.setPlaceholderText(_translate("MainWindow", "Player 1"))
        self.player2.setPlaceholderText(_translate("MainWindow", "Player 2"))
        self.resetgame1.setText(_translate("MainWindow", "Reset"))
        self.score1.setText(_translate("MainWindow", "0"))
        self.score2.setText(_translate("MainWindow", "0"))
        self.resetgame2.setText(_translate("MainWindow", "Reset"))
        self.settime.setText(_translate("MainWindow", "Set time"))
        self.result.setText(_translate("MainWindow", "▼  Result  ▼"))
        self.turn1.setText(_translate("MainWindow", "0"))
        self.turn2.setText(_translate("MainWindow", "0"))
        self.showtime.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.showtime.setPlaceholderText(_translate("MainWindow", "Second"))
        self.l2.setToolTip(_translate("MainWindow", "Views"))
        self.l2.setText(_translate("MainWindow", "1"))
        self.l2_2.setToolTip(_translate("MainWindow", "Views"))
        self.l2_2.setText(_translate("MainWindow", "3"))
        self.l2_3.setToolTip(_translate("MainWindow", "Views"))
        self.l2_3.setText(_translate("MainWindow", "2"))
        self.l2_4.setToolTip(_translate("MainWindow", "Views"))
        self.l2_4.setText(_translate("MainWindow", "4"))
        self.l2_5.setToolTip(_translate("MainWindow", "Views"))
        self.l2_5.setText(_translate("MainWindow", "5"))
        self.l2_6.setToolTip(_translate("MainWindow", "Views"))
        self.l2_6.setText(_translate("MainWindow", "6"))